### ISSUE TITLE
select doesn't accept :class or :disabled attributes

### ISSUE THREAD

**Issue by jcampb** [stouset/twitter_bootstrap_form_for#13]
Maybe I'm missing something...but when I pass class or disabled attributes to the select option, they don't get passed through to the form.

``` erb
<%= f.select(:foo,"Foo",foo_items_for_select,:disabled => true)%>
```

I checked and the attributes do get passed to text_fields

Any ideas on how to include this?

**Comment by stouset** [comment]
You need to provide an empty `options` hash before you can specify options for the `html_options` hash. The method signature for the `select` method in Rails is

``` erb
<%= f.select(method, choices, options = {}, html_options = {}) %>
```

I enhance it with a `label` option, so it becomes

``` erb
<%= f.select(method, label, choices, options = {}, html_options = {}) %>
```

I'm closing this, since this isn't something that's been altered or broken by my gem (best I can tell). Please let me know if this doesn't fix your issue, so I can reopen and investigate.

**Comment by jcampb** [comment]
Great thank you! Sorry noob mistake
